theme: jekyll-theme-tactile
title: Welcome to Alicia's homepage! :) 
description: I am a junior in high-school. I have 6 (almost 7 siblings) and enjoy playing sports such as volleyball or frisbee, playing musical instruments, and hanging out with my family and friends. 
